//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarioQueiros.CodeExercise.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n                [\r\n                {\r\n                \"periodEnd\": \"2015/08/01\"" +
            ",\r\n                \"periodStart\": \"2015/08/01\",\r\n                \"periodTotal\": " +
            "59,\r\n                \"priorPeriodEnd\": \"2015/07/01\",\r\n                \"priorPeri" +
            "odStart\": \"2015/06/01\",\r\n                \"priorPeriodTotal\": 74,\r\n              " +
            "  \"reasonForPeriodDecrease\": \"Loss-leading promo\"\r\n                },\r\n         " +
            "       {\r\n                \"periodEnd\": \"2014/07/01\",\r\n                \"periodSta" +
            "rt\": \"2014/06/01\",\r\n                \"periodTotal\": 45,\r\n                \"priorPe" +
            "riodEnd\": \"2014/06/01\",\r\n                \"priorPeriodStart\": \"2014/05/01\",\r\n    " +
            "            \"priorPeriodTotal\": 74\r\n                },\r\n                {\r\n     " +
            "           \"periodEnd\": \"2015/06/01\",\r\n                \"periodStart\": \"2015/05/0" +
            "1\",\r\n                \"periodTotal\": 37,\r\n                \"priorPeriodEnd\": \"2015" +
            "/05/01\",\r\n                \"priorPeriodStart\": \"2015/05/01\",\r\n                \"pr" +
            "iorPeriodTotal\": 39\r\n                },\r\n                {\r\n                \"per" +
            "iodEnd\": \"2013/05/01\",\r\n                \"periodStart\": \"2013/04/01\",\r\n          " +
            "      \"periodTotal\": 87,\r\n                \"priorPeriodEnd\": \"2013/04/01\",\r\n     " +
            "           \"priorPeriodStart\": \"2013/03/01\",\r\n                \"priorPeriodTotal\"" +
            ": 49\r\n                },\r\n                {\r\n                \"periodEnd\": \"2012/" +
            "03/01\",\r\n                \"periodStart\": \"2012/02/01\",\r\n                \"periodTo" +
            "tal\": 21,\r\n                \"priorPeriodEnd\": \"2012/02/01\",\r\n                \"pri" +
            "orPeriodStart\": \"2012/01/01\",\r\n                \"priorPeriodTotal\": 34,\r\n        " +
            "        \"reasonForPeriodDecrease\": \"Unexpected supplier costs\"\r\n                " +
            "},\r\n                {\r\n                \"periodEnd\": \"2012/10/01\",\r\n             " +
            "   \"periodStart\": \"2012/09/01\",\r\n                \"periodTotal\": 73,\r\n           " +
            "     \"priorPeriodEnd\": \"2012/09/01\",\r\n                \"priorPeriodStart\": \"2012/" +
            "08/01\",\r\n                \"priorPeriodTotal\": 22\r\n                },\r\n           " +
            "     {\r\n                \"periodEnd\": \"2012/04/01\",\r\n                \"periodStart" +
            "\": \"2012/03/01\",\r\n                \"periodTotal\": 73,\r\n                \"priorPeri" +
            "odEnd\": \"2012/03/01\",\r\n                \"priorPeriodStart\": \"2012/02/01\",\r\n      " +
            "          \"priorPeriodTotal\": -22,\r\n                \"reasonForPeriodDecrease\": \"" +
            "Seasonal dip\"\r\n                }\r\n                ]\r\n            ")]
        public string ReportData {
            get {
                return ((string)(this["ReportData"]));
            }
        }
    }
}
